### PR TITLE
Upgrade to 2022.09.02

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Upgrade to 2022.09.02*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
Own result for Revision: fe6b560df0d92bd1aacf1222db57c1b257f57bf0 

image

**Review by FabianWilkens — APPROVED** [review]

**Comment by FabianWilkens** [comment]
I believe that the dev-ci has not enough ram.
I tried it on my CI and I got the same results when not enough ram was available.

**Comment by yalh76** [comment]
> I believe that the dev-ci has not enough ram. I tried it on my CI and I got the same results when not enough ram was available.

I think the same, that's why I made also test on my own CI

**Pull request merged**
