### PR TITLE
Update to 3.22.8

### PR DESCRIPTION
**Pull request by FabianWilkens**
## Problem
- *New version of Standard Notes Syncing Server*
- *New Ruby install script*
- *Typo #17*
- *Wrong permissions*

## Solution
- *Update to new version*
- *Update to new Ruby install script*
- *Fix Typo*
- *Fix Permissions*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by FabianWilkens** [comment]
!testme

**Comment by FabianWilkens** [comment]
!testme

**Comment by SovereignNode** [comment]
Tried to run this branch. Failed
https://paste.yunohost.org/raw/ajecesukug

**Comment by FabianWilkens** [comment]
> Tried to run this branch. Failed
> https://paste.yunohost.org/raw/ajecesukug

You tried the branch ynh_4.2
Which I have created as a fast fix so it is possible to install it on YunoHost 4.2

And this PR is the branch 3.22.8
I am updating the Standard Notes Syncing Server to newer version and also some other improvements.
I think it is already possible for you to install this branch, but the Backup and Restore script seems not to work yet.

**Comment by FabianWilkens** [comment]
Local test was successful.
Package_check results:

snserver_ynh_3 22 8_20210504_000129_results
[snserver_ynh_3.22.8_20210504_000129_results.log](https://github.com/YunoHost-Apps/snserver_ynh/files/6423198/snserver_ynh_3.22.8_20210504_000129_results.log)
[snserver_ynh_3.22.8_20210504_000129_Complete.log](https://github.com/YunoHost-Apps/snserver_ynh/files/6423209/snserver_ynh_3.22.8_20210504_000129_Complete.log)

**Pull request merged**
