### PR TITLE
Upgrade to StandardNotes Standalone 2021.07.06

### PR DESCRIPTION
**Pull request by FabianWilkens**
## Problem

- *Standard Notes syncing-server is deprecated*
- *Delivering old versions of Standard Notes Extensions*
- *https://github.com/YunoHost-Apps/snserver_ynh/issues/27*
- *#29*

## Solution

- *Upgrade to Standard Notes Standalone Infrastructure*
- *Upgrade to Standard Notes Standalone Extensions*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by FabianWilkens** [comment]
!testme

**Comment by FabianWilkens** [comment]
!testme

**Comment by FabianWilkens** [comment]
!testme

**Comment by FabianWilkens** [comment]
@TROMsite
#27 #29 #31 and https://github.com/YunoHost-Apps/snweb_ynh/issues/14
should be working now.

Can you try it please and see if all is good?

**Comment by TROMsite** [comment]
Ok. Sounds great. Should I wait for the ynh repo to update or should I do it manually? If manually let me know more exactly if I should only upgrade the web or also the server.

**Comment by FabianWilkens** [comment]
You can update with this command.
`sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06`
I will look for faults again tomorrow myself.
If everything is fine I'll merge it.

**Comment by TROMsite** [comment]
Well I think I already have that version:

```
sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06
Info: Now upgrading snserver...
Success! snserver is already up-to-date
Success! Upgrade complete
```

**Comment by TROMsite** [comment]
As you remember I upgraded when you last told me and it fixed some of the issues above. Adding repos via the web app didn't work + you have to remove that snserver service.

**Comment by TROMsite** [comment]
The web version I have is 3.6.8~ynh2

**Comment by FabianWilkens** [comment]
> 
> 
> Well I think I already have that version:

Oh yes. Thats because it is the same version in the manifest. But there were changes.
`sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06 --force`

**Comment by TROMsite** [comment]
Ok I forced the upgrade but the web still is at the same verison:
```
admin@tromland:~$ sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06 --force
Info: Now upgrading snserver...
Info: [....................] > Loading installation settings...
Info: [....................] > Backing up the app before upgrading (may take a while)...
Info: [....................] > Stopping a systemd service...
Info: [....................] > Ensuring downward compatibility...
Info: [....................] > Making sure dedicated system user exists...
Info: [+...................] > Upgrading source files...
Info: '/var/www/snserver/help' wasn't deleted because it doesn't exist.
Info: [#...................] > Upgrading nginx web server configuration...
Info: [#...................] > Upgrading dependencies...
Info: '/etc/apt/trusted.gpg.d/snserver.asc' wasn't deleted because it doesn't exist.
Info: [#...................] > Modify a config file...
Info: [#+++++++++++++++++..] > Installing Standard Notes - Syncing Server...
Info: [##################..] > Installing Standard Notes - Extensions...
Info: [##################..] > Upgrading systemd configuration...
Info: [##################..] > Upgrading logrotate configuration...
Info: [##################+.] > Integrate snserver service in Yunohost...
Info: [###################.] > Starting a systemd service...
Info: The service snserver-syncing-server-js has correctly executed the action start.
Info: The service snserver-syncing-server-js-worker has correctly executed the action start.
Info: The service snserver-auth has correctly executed the action start.
Info: The service snserver-auth-worker has correctly executed the action start.
Info: The service snserver-api-gateway has correctly executed the action start.
Info: [###################.] > Reconfiguring fail2ban...
Info: The service fail2ban has correctly executed the action reload-or-restart.
Info: [###################.] > Reloading nginx web server...
Info: [###################.] > Sending a readme for the admin...
Info: [####################] > Upgrade of snserver completed
Success! snserver upgraded
Success! Upgrade complete

```
But now the bug with adding the extensions repo is fixed!

**Comment by FabianWilkens** [comment]
Local Package_Check was successful

Package_check_snserver_20210712_184943
[Package_check_snserver_20210712_184943_Complete.log](https://github.com/YunoHost-Apps/snserver_ynh/files/6803503/Package_check_snserver_20210712_184943_Complete.log)
[Package_check_snserver_20210712_184943_results.json.log](https://github.com/YunoHost-Apps/snserver_ynh/files/6803504/Package_check_snserver_20210712_184943_results.json.log)

**Pull request merged**
